Handin 3 EITN45

TODO: 
- Use the above induction formula to derive the generator matrix G(1, 3).

- List all codewords and determine dmin. How many errors can be corrected? How many errors can be detected?

- Verify that H = G, i.e. that GGT = 0. That means the generator matrix is its own parity check matrix, and such code is said to be self dual.1

- Write the syndrome table for all single errors that can occur on the channel.

- Choose a codeword and introduce a correctable error in it. Decode using the syndrome table.

In [3]:
import sys
import os
sys.path.append(os.path.abspath("../handin1"))
import HandIn1 as h
import numpy as np

In [2]:
IT = h.InfoTheory()


In [3]:
def reed_muller(r, m):
    ''' The function calculates the reed muller 
    '''
    G = np.array([1])
    print(G)

In [4]:
reed_muller()

TypeError: reed_muller() missing 2 required positional arguments: 'r' and 'm'

In [5]:
G = np.array(   [1,0,1,0,1,0,1,0],
                [0,1,0,1,0,1,0,1],
                [0,0,1,1,0,0,1,1],
                [0,0,0,0,1,1,1,1])
                

ValueError: only 2 non-keyword arguments accepted

In [7]:
G = np.array(  [[1,0,1,0,1,0,1,0],
                [0,1,0,1,0,1,0,1],
                [0,0,1,1,0,0,1,1],
                [0,0,0,0,1,1,1,1]])

In [11]:
test = G.dot(G.T)
print(test)

[[4 0 2 2]
 [0 4 2 2]
 [2 2 4 2]
 [2 2 2 4]]


In [12]:
G.T

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 1],
       [1, 0, 1, 1],
       [0, 1, 1, 1]])

In [13]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [54]:
arr = np.array([
            (np.identity(2), np.identity(2)),
            (np.identity(2), np.identity(2))
            ])

In [59]:
arr2 = np.array([
    (arr, arr),
    (np.zeros(pow(2,0)), np.ones(pow(2,0)))
    #[np.zeros(2,1), np.ones(2,1)]
])

In [60]:
print(arr2)

[[array([[[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]],


       [[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]]])
  array([[[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]],


       [[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]]])]
 [array([0.]) array([1.])]]


In [62]:
test = np.identity(pow(2,3))

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [93]:
gh=np.array([
            [np.identity(2)*1, np.identity(2)*2],
            [np.identity(2)*3, np.identity(2)*4]
            ])

In [94]:
print(gh)

[[[[1. 0.]
   [0. 1.]]

  [[2. 0.]
   [0. 2.]]]


 [[[3. 0.]
   [0. 3.]]

  [[4. 0.]
   [0. 4.]]]]


In [95]:
a = [[1, 2, 3], [4, 5, 6]]

In [105]:
np.array([
        a, a
    ])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [40]:
G = np.matrix([
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1],
    [0, 0, 1, 1, 0, 0, 1, 1],
    [0, 0, 0, 0, 1, 1, 1, 1]
])

In [5]:
G*G.T %2

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [6]:
G.T

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 1, 0],
        [0, 1, 1, 0],
        [1, 0, 0, 1],
        [0, 1, 0, 1],
        [1, 0, 1, 1],
        [0, 1, 1, 1]])

In [8]:
lin_comb= np.matrix([
    [0, 0, 0, 0, 0, 0, 0, 0], 
    G,
    [1, 1, 1, 1, 1, 1, 1, 1,]

])

In [9]:
lin_comb

matrix([[list([0, 0, 0, 0, 0, 0, 0, 0]),
         matrix([[1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [0, 0, 1, 1, 0, 0, 1, 1],
        [0, 0, 0, 0, 1, 1, 1, 1]]),
         list([1, 1, 1, 1, 1, 1, 1, 1])]], dtype=object)

In [10]:
lin_comb = np.matrix([
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1],
    [0, 0, 1, 1, 0, 0, 1, 1],
    [0, 0, 0, 0, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 1, 1]

])

In [11]:
lin_comb

matrix([[1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [0, 0, 1, 1, 0, 0, 1, 1],
        [0, 0, 0, 0, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])

In [33]:

def create_binary_list():
    spacewords = []
    for i in range(256):
        l = []
        binary = "{0:b}".format(i)
        zeros = 8 - len(binary)
        for _ in range(zeros):
            l.append(0)
        
        for char in binary: 
            l.append(int(char))
        
        spacewords.append(l)
    
    return spacewords

In [36]:
spacewords = create_binary_list()

To find codewords it must fulfill x*H.T = 0,

In [75]:
H = G 
codewords = []
for word in spacewords: 
    
    number_list = np.matrix(word)*H.T %2
    if number_list.sum() == 0: 
        codewords.append(word)
        print(word)

    

   

<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'num

In [67]:
np.array([1,1])*np.array([2,1])

ValueError: operands could not be broadcast together with shapes (2,) (6,) 

In [71]:
H.T

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 1, 0],
        [0, 1, 1, 0],
        [1, 0, 0, 1],
        [0, 1, 0, 1],
        [1, 0, 1, 1],
        [0, 1, 1, 1]])